# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo 'Hello World' > $(Build.ArtifactStagingDirectory)/helloworld.txt
  displayName: 'Save file as hello world'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/helloworld.txt'
    artifact: 'helloworld.txt'
    publishLocation: 'pipeline'


- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'helloworld.txt'
    targetPath: '$(Pipeline.Workspace)'

- script: |
    cat $(Pipeline.Workspace)/helloworld.txt
  displayName: 'Echo the file saved'